import Menu from './components/Menu';
import Footer from './components/Footer';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
//children é page
export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        {children}
        <Menu/>
        <Footer/>
      </body>
    </html>
  )
}
