import Menu from './components/Menu';
import Route from './api/route';
/* import Footer from './components/Footer'; */
/* import Map from './components/Map'; */
import Link from 'next/link';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
      <Menu/>
      <Route/>
        {children}
        {/* <Footer/> */}
        {/* <Map/> */}
      </body>
    </html>
  )
}
